services:
  sloptoob:
    image: sloptoob:latest
    container_name: slop-docker
    restart: unless-stopped
    environment:
      - PUID=1000
      - GUID=1000
    ports:
    - 3000:3000
    volumes:
      - ./data/.env:/SlopToob/.env 
      - ./data/output:/SlopToob/output
      - ./data/media:/videos
